server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://127.0.0.1:8762/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false